- hosts: localhost
  vars_prompt:
#      - name: y
#        prompt: "enter the time when u want to see the command "
#        private: no
      - name: x
        prompt: "enter the command "
        private: no
      - name: hour
        prompt: "enter the hour "
        private: no
      - name: minutes
        prompt: "enter the minutes "
        private: no

    
  tasks:
    - cron:
        user: root
#        special_time: "{{y}}"
        job: "{{x}}"
        hour: "{{hour}}"
        minute: "{{minutes}}"
        
