- hosts: localhost
  tasks: 
        - name: "Send a mail"
          mail: 
                        host: "smtp.gmail.com"
                        port: "587"
                        username: "sender's_email_id"
                        password: "your_pswd"
                        to: "receiver's_email_id"
                        subject: "Test"
                        body: "Ansible Test Successful"
                        attach: "file_path_to_attach"
          delegate_to: localhost

        
