- hosts: localhost
  tasks:
        - name: "data container"
          docker_container: 
                name: "ansiii"
                image: "imagefire:v1"
                state: started      
                interactive: yes
                tty: yes
                volumes:
                   - /tmp/.X11-unix:/tmp/.X11-unix
#                env_file:
#                   - $DISPLAY: :0
                   
