- hosts: localhost
  tasks:        
       - twilio : 
                msg: "Hello, From twilio."
                account_sid: "your_account_sid"
                auth_token: "your_auth_token"
                from_number: "your_twilio_acnt_number"
                to_number: "your_phone_number"
         delegate_to: localhost
