- hosts: localhost
  tasks:        
       - twilio : 
                msg: "Hello, From twilio."
                account_sid: "AC5186e3d0233838a2236dd8a081a96935"
                auth_token: "079a26d27271e7dbd81bc6283e8c1a9c"
                from_number: "+13082170920"
                to_number: "+91 8209046716"
         delegate_to: localhost
